// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { EditorMode } from "./EditorMode";
import type { EditorSettings } from "./EditorSettings";
import type { SortBy } from "./SortBy";

export type AppSettings = { editorMode: EditorMode, editor: EditorSettings, sortBy: SortBy, };