// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { Category } from "./Category";

export type CategoryWithParent = { category: Category, parent: string | null, };