// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type CategoryNode = { id: string, ctime: string, name: string, children: CategoryNode[], };