// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { CategoryNode } from "./CategoryNode";

export type CategoriesTree = { nodes: Array<CategoryNode>, };