// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { DocumentsFolderChild } from "./DocumentsFolderChild";

export type DocumentsFolderTree = { roots: Array<DocumentsFolderChild>, };