// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { DocumentType } from "./DocumentType";

/**
 * Folder must be created with default tittle `New Document` + {number of default named folders + 1}
 */
export type DocumentForCreate = { title: string, type: DocumentType, };