// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type DocumentsFolderForUpdate = { name: string | null, documents: Array<string> | null, folders: Array<string> | null, };