// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { DocumentsFolderChild } from "./DocumentsFolderChild";

export type DocumentsFolderNode = { id: string, ctime: string, name: string, children: Array<DocumentsFolderChild>, };