// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type DocumentsTemplate = { id: string, ctime: string, name: string, description: string | null, data: string, };