// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { Document } from "./Document";
import type { DocumentsFolderNode } from "./DocumentsFolderNode";

export type DocumentsFolderChild = { "Document": Document } | { "DocumentsFolder": DocumentsFolderNode };