// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type DocumentForUpdate = { title: string | null, body: string | null, tags: Array<string> | null, categories: Array<string> | null, used_pics: Array<string> | null, };