// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type HubEvent<D> = { hub: string, topic: string, label: string | null, data: D | null, };