// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.
import type { IpcError } from "./IpcError";
import type { IpcSimpleResult } from "./IpcSimpleResult";

export type IpcResponse<D> = { error: IpcError | null, result: IpcSimpleResult<D> | null, };