// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

/**
 *
* This type was created mainly for cases like react-select, where such objects are used in the selector.
* The `label` field contains the same content as the `value` field, but formatted
*
 */
export type LabelValue = { label: string, value: string, };