// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

/**
 * For now, all mutation queries will return an {id} struct.
 * Note: Keep it light, and client can do a get if needed.
 */
export type ModelMutateResultData = { id: string, };