// This file was generated by [ts-gen](https://github.com/VlaydDetect/ts-gen). Do not edit this file manually.

export type PictureForUpdate = { name: string | null, desc: string | null, categories: Array<string> | null, tags: Array<string> | null, };