// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorMode } from "./EditorMode";
import type { EditorSettings } from "./EditorSettings";
import type { SortBy } from "./SortBy";

export interface AppSettings { editorMode: EditorMode, editor: EditorSettings, sortBy: SortBy, }