// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CategoryNode { id: string, ctime: string, name: string, children: CategoryNode[], }