// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentsFolderChild } from "./DocumentsFolderChild";

export interface DocumentsFolderTree { roots: Array<DocumentsFolderChild>, }