// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentsFolderChild } from "./DocumentsFolderChild";

export interface DocumentsFolderNode { id: string, ctime: string, name: string, children: Array<DocumentsFolderChild>, }