// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelValue } from "./LabelValue";

export interface DocumentForUpdate { title?: string, body?: string, tags?: Array<LabelValue>, categories?: Array<LabelValue>, used_pics?: Array<string>, }