// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Document } from "./Document";
import type { DocumentsFolderNode } from "./DocumentsFolderNode";

export type DocumentsFolderChild = { "Document": Document } | { "DocumentsFolder": DocumentsFolderNode };