// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Document { id: string, ctime: string, title: string, body?: string, tags?: Array<string>, categories?: Array<string>, used_pics?: Array<string>, }