// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpcError } from "./IpcError";
import type { IpcSimpleResult } from "./IpcSimpleResult";

export interface IpcResponse<D> { error: IpcError | null, result: IpcSimpleResult<D> | null, }