// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Note { id: string, ctime: string, folderId: string, done: boolean, title: string, desc?: string, }