// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PictureForUpdate { title?: string, desc?: string, categories?: Array<string>, tags?: Array<string>, }