// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LabelValue } from "./LabelValue";

export interface PictureForUpdate { title?: string, desc?: string, tags?: Array<LabelValue>, categories?: Array<LabelValue>, }