// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Picture { id: string, ctime: string, img_path: string, title?: string, desc?: string, tags?: Array<string>, categories?: Array<string>, }