// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Volume { name: string, mountpoint: string, availableGb: number, usedGb: number, totalGb: number, }